//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Global Config</summary>
	[PublishedModel("globalConfig")]
	public partial class GlobalConfig : PublishedContentModel, IContactInfromation, IFooter, ITopMenu
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "globalConfig";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GlobalConfig, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public GlobalConfig(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Contact items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("contactItems")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ContactBlock> ContactItems => global::Umbraco.Web.PublishedModels.ContactInfromation.GetContactItems(this);

		///<summary>
		/// Google Map Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("googleMapLink")]
		public string GoogleMapLink => global::Umbraco.Web.PublishedModels.ContactInfromation.GetGoogleMapLink(this);

		///<summary>
		/// Copy Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("copyRight")]
		public global::System.Web.IHtmlString CopyRight => global::Umbraco.Web.PublishedModels.Footer.GetCopyRight(this);

		///<summary>
		/// Footer Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("footerLinks")]
		public global::Umbraco.Core.Models.Blocks.BlockListModel FooterLinks => global::Umbraco.Web.PublishedModels.Footer.GetFooterLinks(this);

		///<summary>
		/// Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("logo")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent Logo => global::Umbraco.Web.PublishedModels.TopMenu.GetLogo(this);

		///<summary>
		/// Navigation menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("navigationMenu")]
		public global::Umbraco.Core.Models.Blocks.BlockListModel NavigationMenu => global::Umbraco.Web.PublishedModels.TopMenu.GetNavigationMenu(this);

		///<summary>
		/// Show Submit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("showSubmit")]
		public bool ShowSubmit => global::Umbraco.Web.PublishedModels.TopMenu.GetShowSubmit(this);

		///<summary>
		/// Social Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("socialLinks")]
		public global::Umbraco.Core.Models.Blocks.BlockListModel SocialLinks => global::Umbraco.Web.PublishedModels.TopMenu.GetSocialLinks(this);

		///<summary>
		/// Top Email
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("topEmail")]
		public string TopEmail => global::Umbraco.Web.PublishedModels.TopMenu.GetTopEmail(this);

		///<summary>
		/// Top Tel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("topTel")]
		public string TopTel => global::Umbraco.Web.PublishedModels.TopMenu.GetTopTel(this);
	}
}
