//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Property Details</summary>
	[PublishedModel("propertyDetails")]
	public partial class PropertyDetails : PublishedContentModel, ICarousel, IContactInfromation, IPageContent, IPageHeader, IPropertyOptions, ISelectAnAgent, ISEO, IShowContent
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "propertyDetails";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PropertyDetails, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PropertyDetails(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Carousel Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("carouselItems")]
		public global::Umbraco.Core.Models.Blocks.BlockListModel CarouselItems => global::Umbraco.Web.PublishedModels.Carousel.GetCarouselItems(this);

		///<summary>
		/// Contact items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("contactItems")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.ContactBlock> ContactItems => global::Umbraco.Web.PublishedModels.ContactInfromation.GetContactItems(this);

		///<summary>
		/// Google Map Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("googleMapLink")]
		public string GoogleMapLink => global::Umbraco.Web.PublishedModels.ContactInfromation.GetGoogleMapLink(this);

		///<summary>
		/// Content Grid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageContentGrid")]
		public global::Newtonsoft.Json.Linq.JToken PageContentGrid => global::Umbraco.Web.PublishedModels.PageContent.GetPageContentGrid(this);

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("headerImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeaderImage => global::Umbraco.Web.PublishedModels.PageHeader.GetHeaderImage(this);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => global::Umbraco.Web.PublishedModels.PageHeader.GetPageTitle(this);

		///<summary>
		/// Amenity Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("amenityItems")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.AmenityIterm> AmenityItems => global::Umbraco.Web.PublishedModels.PropertyOptions.GetAmenityItems(this);

		///<summary>
		/// Bathrooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bathrooms")]
		public string Bathrooms => global::Umbraco.Web.PublishedModels.PropertyOptions.GetBathrooms(this);

		///<summary>
		/// Bedrooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bedrooms")]
		public string Bedrooms => global::Umbraco.Web.PublishedModels.PropertyOptions.GetBedrooms(this);

		///<summary>
		/// Contract type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("contractType")]
		public string ContractType => global::Umbraco.Web.PublishedModels.PropertyOptions.GetContractType(this);

		///<summary>
		/// Floor Plan
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("floorPlan")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent FloorPlan => global::Umbraco.Web.PublishedModels.PropertyOptions.GetFloorPlan(this);

		///<summary>
		/// Garages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("garages")]
		public string Garages => global::Umbraco.Web.PublishedModels.PropertyOptions.GetGarages(this);

		///<summary>
		/// Google Map Location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("googleMapLocation")]
		public string GoogleMapLocation => global::Umbraco.Web.PublishedModels.PropertyOptions.GetGoogleMapLocation(this);

		///<summary>
		/// Home Area
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("homeArea")]
		public int HomeArea => global::Umbraco.Web.PublishedModels.PropertyOptions.GetHomeArea(this);

		///<summary>
		/// Parking lots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("parkingLots")]
		public string ParkingLots => global::Umbraco.Web.PublishedModels.PropertyOptions.GetParkingLots(this);

		///<summary>
		/// Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("price")]
		public int Price => global::Umbraco.Web.PublishedModels.PropertyOptions.GetPrice(this);

		///<summary>
		/// City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("propertyCity")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PropertyCity => global::Umbraco.Web.PublishedModels.PropertyOptions.GetPropertyCity(this);

		///<summary>
		/// Province
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("propertyProvince")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PropertyProvince => global::Umbraco.Web.PublishedModels.PropertyOptions.GetPropertyProvince(this);

		///<summary>
		/// Sub City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("propertySubcity")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PropertySubcity => global::Umbraco.Web.PublishedModels.PropertyOptions.GetPropertySubcity(this);

		///<summary>
		/// Property Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("propertyType")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PropertyType => global::Umbraco.Web.PublishedModels.PropertyOptions.GetPropertyType(this);

		///<summary>
		/// Rooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("rooms")]
		public string Rooms => global::Umbraco.Web.PublishedModels.PropertyOptions.GetRooms(this);

		///<summary>
		/// Year Built
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("yearBuilt")]
		public int YearBuilt => global::Umbraco.Web.PublishedModels.PropertyOptions.GetYearBuilt(this);

		///<summary>
		/// Select Agent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("selectAgent")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent SelectAgent => global::Umbraco.Web.PublishedModels.SelectAnAgent.GetSelectAgent(this);

		///<summary>
		/// Seo Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle => global::Umbraco.Web.PublishedModels.SEO.GetSeoTitle(this);

		///<summary>
		/// Show Blogs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("showBlogs")]
		public bool ShowBlogs => global::Umbraco.Web.PublishedModels.ShowContent.GetShowBlogs(this);
	}
}
