//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "propertyOptions"
	/// <summary>Property Options</summary>
	public partial interface IPropertyOptions : IPublishedContent
	{
		/// <summary>Amenity Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.AmenityIterm> AmenityItems { get; }

		/// <summary>Bathrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Bathrooms { get; }

		/// <summary>Bedrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Bedrooms { get; }

		/// <summary>Contract type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string ContractType { get; }

		/// <summary>Floor Plan</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent FloorPlan { get; }

		/// <summary>Garages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Garages { get; }

		/// <summary>Google Map Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string GoogleMapLocation { get; }

		/// <summary>Home Area</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		int HomeArea { get; }

		/// <summary>Location Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string LocationType { get; }

		/// <summary>Parking lots</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string ParkingLots { get; }

		/// <summary>Price</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		int Price { get; }

		/// <summary>Property Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string PropertyType { get; }

		/// <summary>Province</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Province { get; }

		/// <summary>Rooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		string Rooms { get; }

		/// <summary>Year Built</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		int YearBuilt { get; }
	}

	/// <summary>Property Options</summary>
	[PublishedModel("propertyOptions")]
	public partial class PropertyOptions : PublishedContentModel, IPropertyOptions
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "propertyOptions";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PropertyOptions, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PropertyOptions(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Amenity Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("amenityItems")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.AmenityIterm> AmenityItems => GetAmenityItems(this);

		/// <summary>Static getter for Amenity Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.AmenityIterm> GetAmenityItems(IPropertyOptions that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.AmenityIterm>>("amenityItems");

		///<summary>
		/// Bathrooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bathrooms")]
		public string Bathrooms => GetBathrooms(this);

		/// <summary>Static getter for Bathrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetBathrooms(IPropertyOptions that) => that.Value<string>("bathrooms");

		///<summary>
		/// Bedrooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bedrooms")]
		public string Bedrooms => GetBedrooms(this);

		/// <summary>Static getter for Bedrooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetBedrooms(IPropertyOptions that) => that.Value<string>("bedrooms");

		///<summary>
		/// Contract type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("contractType")]
		public string ContractType => GetContractType(this);

		/// <summary>Static getter for Contract type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetContractType(IPropertyOptions that) => that.Value<string>("contractType");

		///<summary>
		/// Floor Plan
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("floorPlan")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent FloorPlan => GetFloorPlan(this);

		/// <summary>Static getter for Floor Plan</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetFloorPlan(IPropertyOptions that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("floorPlan");

		///<summary>
		/// Garages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("garages")]
		public string Garages => GetGarages(this);

		/// <summary>Static getter for Garages</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetGarages(IPropertyOptions that) => that.Value<string>("garages");

		///<summary>
		/// Google Map Location
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("googleMapLocation")]
		public string GoogleMapLocation => GetGoogleMapLocation(this);

		/// <summary>Static getter for Google Map Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetGoogleMapLocation(IPropertyOptions that) => that.Value<string>("googleMapLocation");

		///<summary>
		/// Home Area
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("homeArea")]
		public int HomeArea => GetHomeArea(this);

		/// <summary>Static getter for Home Area</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static int GetHomeArea(IPropertyOptions that) => that.Value<int>("homeArea");

		///<summary>
		/// Location Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("locationType")]
		public string LocationType => GetLocationType(this);

		/// <summary>Static getter for Location Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetLocationType(IPropertyOptions that) => that.Value<string>("locationType");

		///<summary>
		/// Parking lots
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("parkingLots")]
		public string ParkingLots => GetParkingLots(this);

		/// <summary>Static getter for Parking lots</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetParkingLots(IPropertyOptions that) => that.Value<string>("parkingLots");

		///<summary>
		/// Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("price")]
		public int Price => GetPrice(this);

		/// <summary>Static getter for Price</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static int GetPrice(IPropertyOptions that) => that.Value<int>("price");

		///<summary>
		/// Property Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("propertyType")]
		public string PropertyType => GetPropertyType(this);

		/// <summary>Static getter for Property Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetPropertyType(IPropertyOptions that) => that.Value<string>("propertyType");

		///<summary>
		/// Province
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("province")]
		public string Province => GetProvince(this);

		/// <summary>Static getter for Province</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetProvince(IPropertyOptions that) => that.Value<string>("province");

		///<summary>
		/// Rooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("rooms")]
		public string Rooms => GetRooms(this);

		/// <summary>Static getter for Rooms</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static string GetRooms(IPropertyOptions that) => that.Value<string>("rooms");

		///<summary>
		/// Year Built
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("yearBuilt")]
		public int YearBuilt => GetYearBuilt(this);

		/// <summary>Static getter for Year Built</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static int GetYearBuilt(IPropertyOptions that) => that.Value<int>("yearBuilt");
	}
}
